services:
    sql:
        image: mcr.microsoft.com/azure-sql-edge
        environment:
            ACCEPT_EULA: "1"
            MSSQL_SA_PASSWORD: "Crispusmunene@356"
        ports:
            - "1433:1433"